import './style.css';
import { AdMob, BannerAdSize, BannerAdPosition } from '@capacitor-community/admob';
const IDS={app:'ca-app-pub-995853981287899~2242325345',banner:'ca-app-pub-995853981287899/1507828173',interstitial:'ca-app-pub-995853981287899/4293773610',rewarded:'ca-app-pub-995853981287899/8400364577'};
const $=id=>document.getElementById(id), native=()=>!!window.Capacitor?.isNativePlatform?.();
let screen='home',g=null,raf=0,last=0,elapsed=0,duration=120,homeScore=0,awayScore=0,paused=false,finished=0,joy={x:0,y:0},sprint=false;
async function adsInit(){if(!native())return;try{await AdMob.initialize({initializeForTesting:true});}catch(e){console.warn(e)}}
async function banner(show){if(!native())return;try{if(show)await AdMob.showBanner({adId:IDS.banner,adSize:BannerAdSize.ADAPTIVE_BANNER,position:BannerAdPosition.BOTTOM_CENTER,isTesting:true});else await AdMob.hideBanner()}catch(e){console.warn(e)}}
function page(s){screen=s;['home','game','settings'].forEach(x=>$(x).classList.toggle('hidden',x!==s));$('adslot').classList.toggle('hide',s!=='home');if(s==='home')banner(true);else banner(false);if(s==='game'&&g)resize()}
function start(type='pes'){elapsed=0;homeScore=awayScore=0;paused=false;$('ht').textContent='BAR';$('at').textContent=type==='fifa'?'BAY':'RMA';$('score').textContent='0 - 0';$('clock').textContent='00:00';$('pauseMenu').classList.add('hidden');$('endMenu').classList.add('hidden');page('game');g=create();last=performance.now();cancelAnimationFrame(raf);raf=requestAnimationFrame(loop)}
function create(){let c=$('pitch'),r=c.getBoundingClientRect();c.width=Math.max(320,r.width*devicePixelRatio);c.height=Math.max(270,r.height*devicePixelRatio);let w=c.width,h=c.height,ps=[];for(let t=0;t<2;t++)for(let i=0;i<7;i++){let row=Math.floor(i/3),col=i%3;ps.push({t,i,x:w*(t?.88-col*.12:.12+col*.12),y:h*(.2+row*.3+(col===1?-.03:.03)),st:100,n:[10,7,8,6,3,4,1][i],r:w*.012})}return{w,h,ps,b:{x:w/2,y:h/2,vx:0,vy:0,o:-1,r:w*.007},user:0}}
function resize(){if(!g)return;let old=g;g=create();g.ps.forEach((p,i)=>{p.x=old.ps[i].x/old.w*g.w;p.y=old.ps[i].y/old.h*g.h});g.b.x=old.b.x/old.w*g.w;g.b.y=old.b.y/old.h*g.h}
const d=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function pass(){if(!g||paused)return;let p=g.ps[g.user],q=g.ps.filter((x,i)=>x.t===0&&i!==g.user).sort((a,b)=>d(a,p)-d(b,p))[0];if(q){g.b={...g.b,x:p.x,y:p.y,vx:(q.x-p.x)*1.6,vy:(q.y-p.y)*1.6,o:-1}}}
function shoot(){if(!g||paused)return;let p=g.ps[g.user],dx=g.w*.98-p.x,dy=g.h/2-p.y,l=Math.hypot(dx,dy)||1;g.b={...g.b,x:p.x,y:p.y,vx:dx/l*g.w*.62,vy:dy/l*g.h*.42,o:-1}}
function tackle(){if(!g||paused)return;let p=g.ps[g.user],q=g.ps.filter(x=>x.t===1).sort((a,b)=>d(a,p)-d(b,p))[0];if(q&&d(q,p)<g.w*.16){g.b.o=g.user;g.b.x=p.x;g.b.y=p.y}}
function update(dt){if(!g||paused)return;let {w,h,ps,b}=g,p=ps[g.user],spd=w*(sprint?0.43:0.3);p.x=clamp(p.x+joy.x*spd*dt,w*.04,w*.96);p.y=clamp(p.y+joy.y*spd*dt,h*.05,h*.95);p.st=clamp(p.st+(sprint?-dt*10:dt*3),10,100);$('stamina').style.width=p.st+'%';
ps.forEach((q,i)=>{if(i===g.user)return;let tx,ty;if(q.t===1){tx=b.x;ty=b.y}else{tx=w*.18+(i%3)*w*.12;ty=h*(.2+Math.floor(i/3)*.3);if(b.o<0&&d(q,b)<w*.35){tx=b.x;ty=b.y}}let dx=tx-q.x,dy=ty-q.y,l=Math.hypot(dx,dy)||1,s=w*(q.t===1?0.19:0.11);q.x=clamp(q.x+dx/l*s*dt,w*.03,w*.97);q.y=clamp(q.y+dy/l*s*dt,h*.05,h*.95)});
if(b.o===g.user){b.x=p.x+p.r;b.y=p.y;b.vx=p.vx||0;b.vy=0}else{b.x+=b.vx*dt;b.y+=b.vy*dt;b.vx*=Math.pow(.985,dt*60);b.vy*=Math.pow(.985,dt*60);if(b.y<0||b.y>h)b.vy*=-.8;let near=ps.map((q,i)=>({q,i,dist:d(q,b)})).sort((a,b)=>a.dist-b.dist)[0];if(near&&near.dist<near.q.r+b.r+3&&Math.hypot(b.vx,b.vy)<w*.35){b.o=near.i;b.vx=b.vy=0;if(near.q.t===0)g.user=near.i}}
if(b.x>w*.97&&Math.abs(b.y-h/2)<h*.17){homeScore++;reset()}if(b.x<w*.03&&Math.abs(b.y-h/2)<h*.17){awayScore++;reset()}elapsed+=dt;$('score').textContent=homeScore+' - '+awayScore;let s=Math.floor(elapsed);$('clock').textContent=String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0');if(elapsed>=duration)end()}
function reset(){g.b={...g.b,x:g.w/2,y:g.h/2,vx:0,vy:0,o:-1}}
function end(){cancelAnimationFrame(raf);finished++;$('finalScore').textContent=homeScore+' - '+awayScore;$('result').textContent=homeScore>awayScore?'Victory!':homeScore===awayScore?'A draw.':'Try again!';$('endMenu').classList.remove('hidden');if(native()&&finished%2===0)AdMob.prepareInterstitial({adId:IDS.interstitial,isTesting:true}).then(()=>AdMob.showInterstitial()).catch(console.warn)}
function loop(now){let dt=Math.min(.04,(now-last)/1000||0);last=now;update(dt);draw();if(screen==='game'&&!paused&&!$('endMenu').classList.contains('hidden')===false)raf=requestAnimationFrame(loop);else if(screen==='game'&&!paused&&$('endMenu').classList.contains('hidden'))raf=requestAnimationFrame(loop)}
function draw(){if(!g)return;let c=$('pitch'),x=c.getContext('2d'),w=g.w,h=g.h,b=g.b;x.clearRect(0,0,w,h);for(let i=0;i<8;i++){x.fillStyle=i%2?'#19783b':'#228747';x.fillRect(w*.035+i*w*.116,h*.035,w*.116,h*.93)}x.fillStyle='#102a3d';x.fillRect(0,0,w,h*.05);x.fillRect(0,h*.95,w,h*.05);x.strokeStyle='#eaffef';x.lineWidth=Math.max(1,w*.0025);x.strokeRect(w*.035,h*.06,w*.93,h*.88);x.beginPath();x.moveTo(w/2,h*.06);x.lineTo(w/2,h*.94);x.stroke();x.beginPath();x.arc(w/2,h/2,h*.13,0,7);x.stroke();x.strokeRect(w*.035,h*.31,w*.16,h*.38);x.strokeRect(w*.805,h*.31,w*.16,h*.38);g.ps.forEach((p,i)=>{x.fillStyle=p.t?'#f5f7fa':'#145cff';x.beginPath();x.arc(p.x,p.y,p.r,0,7);x.fill();x.strokeStyle=p.t?'#ff6078':'#6de4ff';x.stroke();x.fillStyle=p.t?'#d83b55':'#ffdb38';x.fillRect(p.x-p.r*.4,p.y-p.r*.2,p.r*.8,p.r*.3);if(i===g.user){x.fillStyle='#00ff88';x.beginPath();x.moveTo(p.x,p.y-p.r-5);x.lineTo(p.x-4,p.y-p.r-12);x.lineTo(p.x+4,p.y-p.r-12);x.fill()}x.fillStyle='#00ff88';x.fillRect(p.x-p.r,p.y+p.r+2,p.r*2*p.st/100,3)});x.fillStyle='#fff';x.beginPath();x.arc(b.x,b.y,b.r,0,7);x.fill();x.strokeStyle='#111';x.stroke();let rx=w*.4,ry=h*.82,rw=w*.2,rh=h*.12;x.fillStyle='#041322cc';x.fillRect(rx,ry,rw,rh);x.strokeStyle='#d9f7ff';x.strokeRect(rx,ry,rw,rh);g.ps.forEach(p=>{x.fillStyle=p.t?'#ff5874':'#00ff88';x.beginPath();x.arc(rx+p.x/w*rw,ry+p.y/h*rh,2,0,7);x.fill()})}
function joyMove(e){let r=$('joy').getBoundingClientRect(),dx=(e.clientX-r.left-r.width/2)/(r.width*.38),dy=(e.clientY-r.top-r.height/2)/(r.height*.38),l=Math.hypot(dx,dy)||1;if(l>1){dx/=l;dy/=l}joy={x:dx,y:dy};$('knob').style.transform=`translate(${dx*22}px,${dy*22}px)`}
function joyReset(){joy={x:0,y:0};$('knob').style.transform='translate(0,0)'}
$('joy').onpointerdown=e=>{e.preventDefault();$('joy').setPointerCapture(e.pointerId);joyMove(e)};$('joy').onpointermove=e=>{if(e.buttons)joyMove(e)};$('joy').onpointerup=joyReset;$('joy').onpointercancel=joyReset;
$('pass').onpointerdown=pass;$('shoot').onpointerdown=shoot;$('tackle').onpointerdown=tackle;$('sprint').onpointerdown=()=>sprint=true;$('sprint').onpointerup=()=>sprint=false;$('sprint').onpointercancel=()=>sprint=false;
$('kick').onclick=()=>start('pes');document.querySelectorAll('[data-match]').forEach(b=>b.onclick=()=>start(b.dataset.match));$('playNav').onclick=()=>start('pes');$('homeNav').onclick=()=>page('home');$('settingsBtn').onclick=$('settingsNav').onclick=()=>page('settings');$('duration').onchange=e=>duration=+e.target.value;
$('pause').onclick=()=>{paused=true;$('pauseMenu').classList.remove('hidden')};$('resume').onclick=()=>{paused=false;$('pauseMenu').classList.add('hidden');last=performance.now();raf=requestAnimationFrame(loop)};$('restart').onclick=()=>start('pes');$('quit').onclick=()=>{paused=false;cancelAnimationFrame(raf);page('home')};$('again').onclick=()=>start('pes');$('endHome').onclick=()=>{cancelAnimationFrame(raf);$('endMenu').classList.add('hidden');page('home')};
page('home');adsInit();
